services:
  - type: web
    name: i-hybrid-chatbot-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FRONTEND_ORIGIN
        value: http://localhost:8000
